### ISSUE TITLE
SSL Certificate not valid: host name mismatch

### ISSUE THREAD

**Issue by agustif** [mxgrn/pairs.one#11]
MacOS High Sierra, Safari, moans about SSL
<img width="711" alt="screenshot 2017-10-22 17 31 17" src="https://user-images.githubusercontent.com/6601142/31863524-e214d54e-b74e-11e7-8315-4a5697c2dea9.png">

**Comment by mxgrn** [comment]
@agustif Please, try HTTP for now: http://pairs.one - will fix HTTPS soon.

**Comment by mxgrn** [comment]
This has been fixed @agustif !
