### ISSUE TITLE
Copyright company URL no longer valid?

### ISSUE THREAD

**Issue by Nezteb** [mxgrn/pairs.one#33]
> Copyright (c) 2017 [Good Bit Labs Limited](http://goodbitlabs.com/), released under MIT

http://goodbitlabs.com/ leads to a strange site that I don't believe you are actually affiliated with?

![64ad9d2c6d7046190822943a](https://github.com/mxgrn/pairs.one/assets/3588798/4024487a-9a7e-4553-94c3-c4eeca2b943b)

That copyright statement and URL should probably be modified? 😅

**Comment by mxgrn** [comment]
Hey, thanks, it was once my consultancy site. Fixed now, pointing to my personal site.
