### ISSUE TITLE
ES Translation

### ISSUE THREAD

**Issue by agustif** [mxgrn/pairs.one#5]
Is it ok if I push a PR with ES translation without accents? Im on a US keyboard and always tanked orthography anyways.

What'd ya think?

**Comment by mxgrn** [comment]
Sure, it's much better than no translation at all! :) And if someone misses the accents, they may do a PR as well.

However, I'd suggest to wait a little bit until I release a "2.0" version with a redesign and a few new cool features (such as possibility to join a random game). Should be out around this weekend, it's already in the field testing :)

**Comment by agustif** [comment]
Kay! will wait

**Comment by mxgrn** [comment]
Well, it took a bit longer :), but it's online now. I slightly updated the translations section in the README, so, if you're still up to this, @agustif , it would be awesome! Thanks)

**Comment by agustif** [comment]
@mxgrn Sure Max, I will take a look, it will be nice for getting the shirts on Hacktoberfest

**Comment by mxgrn** [comment]
Hey hey @agustif - any chance we can still wrap this up? :) Or too busy nowadays?

**Comment by mxgrn** [comment]
Done. Closing.
